#!/bin/bash

absolute_data_path="/Users/James/code/skyway2020/src/skyway2021/data"

cd $absolute_data_path

echo "Removing.."
ls -tp | grep -v '/$' | tail -n +6 

ls -tp | grep -v '/$' | tail -n +6 | xargs -I {} rm -- {}

